export const API_ENDPOINTS = {
  LOGIN: '/user/login/',
  REGISTER: '/user/register/',
  FORGET_PASSWORD: '/user/forgotPassword/',
  RESET_PASSWORD: '/user/resetPassword/',
  USER: `/user/profile/`,
  UPDATE_USER: `/user/updateUser/`,
  CHANGE_PASSWORD: '/user/changePassword/',
  ADDRESS: '/user/address/',
  PRODUCTS: '/item/',
  EMAIL_VERIFICATION: '/user/activation/',
  ORDERS: '/order/', // fsdfsdfsfsdfsdfsdsdffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  ORDER: '/order/',
  CATEGORIES: '/category/',
  PRODUCTS_BY_CATEGORY: '/category/categoryItem/',
  SEARCH_PRODUCTS: '/search',
  // Default end points.

  LOGOUT: '/logout',
  // CATEGORIES: '/categories.json',

  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  // PRODUCTS: '/products.json',
  PRODUCT: '/product.json',
  RELATED_PRODUCTS: '/related_products.json',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',
  BEST_SELLER_GROCERY_PRODUCTS: '/products_best_seller_grocery.json',
  POPULAR_PRODUCTS: '/products_popular.json',
  COOKIES_PRODUCTS: '/products_cookies.json',
  CHIPS_PRODUCTS: '/products_chips.json',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/products_fresh_vegetables.json',
  SEARCH: '/search.json',
  // ORDERS: '/orders.json',
  // ORDER: '/order.json',
  ORDER_STATUS: '/order-status.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/shops.json',
  WISHLIST: '/wishlist.json',
};
